### ISSUE TITLE
Default Deny policy is created with ingress allow

### ISSUE THREAD

**Issue by emptywee** [projectcalico/kube-controllers#198]
## Current Behavior

(I combed thru the closed issues related to this, but nothing there was applicable to my case, imho. So this is more like a support request here.)

Recently I have upgraded my self-hosted kubernetes cluster from 1.6 to 1.7. The most important change there was those Network Policies. Earlier I was using kube-policy-controller 0.6.0 and calico-node 2.4.1 with namespace annotations. And it was working. Now with the upgrade of Kubernetes I also upgraded calico-node to 2.6.3 and kube-controllers to v1.0.1.

Wherever I had those defaultdeny annotations, it's not denying anything anymore, which is expected. I decided to try it out first on a test namespace. The namespace has no annotations:

```
$ kubectl describe ns spinnaker-lab
Name:           spinnaker-lab
Labels:         <none>
Annotations:    <none>
Status:         Active

No resource quota.

No resource limits.
```

The following network policy has been created:
```
$ kubectl --namespace=spinnaker-lab get networkpolicy default-deny -o yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"default-deny","namespace":"spinnaker-lab"},"spec":{"podSelector":{}}}
  creationTimestamp: 2017-12-02T01:43:45Z
  generation: 2
  name: default-deny
  namespace: spinnaker-lab
  resourceVersion: "77444977"
  selfLink: /apis/extensions/v1beta1/namespaces/spinnaker-lab/networkpolicies/default-deny
  uid: 3be1cd5a-d702-11e7-8f71-005056806114
spec:
  podSelector: {}
```

I am seeing that the policy controller created an entry:
```
knp.default.spinnaker-lab.default-deny      1000    calico/k8s_ns == 'spinnaker-lab'
```

But that entry is kinda not what I expect it to be:
```
# ./calicoctl get policy knp.default.spinnaker-lab.default-deny -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.spinnaker-lab.default-deny
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'spinnaker-lab'
```

## Expected Behavior

I expect it to create a differently looking policy and block ingress traffic.

## Context
Trying to block all ingress traffic and allow only what should be allowed.

## Your Environment

* Kubernetes version (`kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.11+coreos.0", GitCommit:"90636164328fc267b9457fa619872ce4f3432f39", GitTreeState:"clean", BuildDate:"2017-11-29T10:28:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* Manifest file used to deploy k8s policy:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: spinnaker-lab
spec:
  podSelector: {}
```
* Operating System and version: running a self-hosted Kubernetes 1.7.11 on CoreOS . More information on request (just don't know what info is relevant to this, and also don't want to overload the ticket).
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1520.9.0
VERSION_ID=1520.9.0
BUILD_ID=2017-11-30-1105
PRETTY_NAME="Container Linux by CoreOS 1520.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

**Comment by emptywee** [comment]
Sorry, @caseydavenport , my bad. That node still had 1.4.1, while the rest of them had 1.6.2.

Here's the 1.6.2 output:
```
# ./calicoctl get policy knp.default.spinnaker-lab.default-deny -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: knp.default.spinnaker-lab.default-deny
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    order: 1000
    selector: calico/k8s_ns == 'spinnaker-lab'
    types:
    - ingress
```

**Comment by emptywee** [comment]
calicoctl version output:
```
 ./calicoctl version
Client Version:    v1.6.2
Build date:        2017-11-22T22:41:27+0000
Git commit:        855392a8
Cluster Version:   v2.6.3
Cluster Type:      k8s,bgp
```

**Comment by emptywee** [comment]
And yes, traffic is not blocked. I can freely get to the pods in that namespace after all.

**Comment by emptywee** [comment]
@caseydavenport so with the new output from calicoctl 1.6.2, how do I read it? It is saying to allow egress, which is fine. It has *types* set to "ingress", though. What does it mean? Is it supposed to allow egress traffic, but block ingress? In other words, is it how it is supposed to look when I have a default deny ingress policy created?

**Comment by caseydavenport** [comment]
@emptywee yes, that policy is pretty confusing, but was done like that in order to support upgrade / mixed versions properly. 

Earlier versions of Felix don't understand the "types" field, and so to them this policy looks like an allow-egress, deny-ingress policy.

Newer versions of Felix respect the types field, and so they see this as a "don't-impact-egress" and "deny-ingress" policy.

So in summary, I'd expect this policy to be doing the right thing, but it sounds like it isn't and thus needs more investigation :)

**Comment by caseydavenport** [comment]
For completeness, could you also show the yaml for the workload endpoint that this is meant to select via `calicoctl get wep`?

**Comment by emptywee** [comment]
@caseydavenport yeah, first I was thinking it was just the policy not being created correctly, but now seems like the policy is correct, but something is still allowing traffic. I have a bunch of rules that I made with kube policy manager 0.6.0 previously, but they have no relation to this test namespace.

So, to answer your question, here they are:

```
rnqkbw403 bin # ./calicoctl get wep | grep spinnaker-lab
rnqkbw401   k8s            spinnaker-lab.spin-fiat-3385378692-fv3w4              eth0
rnqkbw401   k8s            spinnaker-lab.spin-igor-1573768239-4tmts              eth0
rnqkbw401   k8s            spinnaker-lab.spin-orca-1                             eth0
rnqkbw402   k8s            spinnaker-lab.spin-deck-3811475939-5j6ts              eth0
rnqkbw403   k8s            spinnaker-lab.spin-deck-3811475939-ttthk              eth0
rnqkbw403   k8s            spinnaker-lab.spin-gate-979888209-f9w7t               eth0
rnqkbw406   k8s            spinnaker-lab.spin-fiat-3385378692-t7fcb              eth0
rnqkbw406   k8s            spinnaker-lab.spin-gate-979888209-g546f               eth0
rnqkbw406   k8s            spinnaker-lab.spin-igor-1573768239-9v4pc              eth0
rnqkbw406   k8s            spinnaker-lab.spin-orca-0                             eth0
```
All those guys are supposed to get secured in terms of incoming connections.

Currently I am trying to telnet to port 8084 of this one:
```
rnqkbw403 bin # ./calicoctl get wep --workload=spinnaker-lab.spin-gate-979888209-f9w7t -o yaml
- apiVersion: v1
  kind: workloadEndpoint
  metadata:
    activeInstanceID: 033ca6ae3a6d686ebec750a1f5d553750d4fb6bfe7c45e5319ca1e1471b81041
    labels:
      app: gate
      calico/k8s_ns: spinnaker-lab
      load-balancer-spin-gate: "true"
      pod-template-hash: "979888209"
    name: eth0
    node: rnqkbw403
    orchestrator: k8s
    workload: spinnaker-lab.spin-gate-979888209-f9w7t
  spec:
    interfaceName: cali1f5a29e647c
    ipNetworks:
    - 10.148.212.94/32
    mac: 02:b6:54:41:ca:a0
    profiles:
    - k8s_ns.spinnaker-lab
```
And I am able to do, despite having that default deny rule in place.
