### ISSUE TITLE
Kubernetes Network Policies not correctly transformed into calico policies

### ISSUE THREAD

**Issue by corest** [projectcalico/kube-controllers#379]
While trying to block certain ingress traffic in kubernetes pod, my policy doesn't work as expected.

## Expected Behavior
No pods can get metrics from coredns.

## Current Behavior
Any pod still can get metrics from coredns on port 9153.

## Steps to Reproduce (for bugs)
I have `coredns` pod in `kube-system` namespace. It has two ports opened: `53` for dns and `9153` for prometheus metrics. 

With this policy I'm blocking all the traffic from getting into `coredns`
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-all-app
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  ingress: []
```

With this policy I'm allowing access to port `53` from all pods in the cluster:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: kube-system
  name: coredns-allow-dns-from-all-namespaces
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - from:
    - namespaceSelector: {}
```

I checked the resulting policy in calico

```
spec:
  ingress:
  - action: Allow
    destination:
      ports:
      - 53
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      ports:
      - 53
    protocol: TCP
    source: {}
  - action: Allow
    destination: {}
    source:
      namespaceSelector: all()
      selector: projectcalico.org/orchestrator == 'k8s'
  order: 1000
  selector: projectcalico.org/orchestrator == 'k8s' && k8s-app == 'coredns'
  types:
  - Ingress
```

It doesn't look right. The last allow action actually makes first two useless. From the policies above I would expect to have
```
spec:
  ingress:
  - action: Allow
    destination:
      ports:
      - 53
    protocol: UDP
    source:
      namespaceSelector: all()
      selector: projectcalico.org/orchestrator == 'k8s'
  - action: Allow
    destination:
      ports:
      - 53
    protocol: TCP
    source:
      namespaceSelector: all()
      selector: projectcalico.org/orchestrator == 'k8s'
  order: 1000
  selector: projectcalico.org/orchestrator == 'k8s' && k8s-app == 'coredns'
  types:
  - Ingress
```

Am I missing something?

## Your Environment
* Calico version 3.6.1
* Orchestrator version (e.g. kubernetes, mesos, rkt): kubernetes 1.14.1
* Operating System and version: CoreOS 2023.04

**Comment by corest** [comment]
It is me being dumb. Sorry. Rule should be constructed in this way:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: kube-system
  name: coredns-allow-dns-from-all-namespaces
spec:
  podSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    from:
    - namespaceSelector: {}
```
